# For more configuration details:
# https://docs.codecov.io/docs/codecov-yaml

# Check if this file is valid by running in bash:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

# Coverage configuration
# ----------------------
# Global YAML [lower on hierarchy]
# The user that you will use to serve as the bot connection to Codecov
# This bot user must have permissions on the repo and Codecov (by logging in)

codecov:
  bot: <bot-SwaragThaikkandi> #this is a username for Github/Gitlab/Bitbucket
  notify:
    manual_trigger: true
  

coverage:
  round: down
  precision: 5

# Repository YAML [higher on hierarchy]
coverage:
  round: up
  range: 0..10

# Used in Codecov after updating
coverage:
  round: up
  range: 0..10
  precision: 5
# Ignoring Paths
# --------------
# which folders/files to ignore
ignore:
  - *SMdRQA/tests/.*
  - setup.py
  - versioneer.py

# Pull request comments:
# ----------------------
# Diff is the Coverage Diff of the pull request.
# Files are the files impacted by the pull request
comment:
  layout: diff, files  # accepted in any order: reach, diff, flags, and/or files

comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment
  
component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: RQA_functions
      paths:
        - .*/SMdRQA/RQA_functions.py
    - component_id: RP_maker
      paths:
        - .*/SMdRQA/RP_maker.py
    - component_id: Extract_RP
      paths:
        - .*/SMdRQA/Extract_from_RP.py
    - component_id: RP_maker_diagnose
      paths:
        - .*/SMdRQA/RP_maker_diagnose.py
    - component_id: cross_validation
      paths:
        - .*/SMdRQA/cross_validation.py
    - component_id: nl_test
      paths:
        - .*/SMdRQA/nl_tests.py
    - component_id: window_size
      paths:
        - .*/SMdRQA/window_size.py
    - component_id: Utilities
      paths:
        - .*/SMdRQA/utils.py
