name: base
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - tqdm
  - pip
  - memory_profiler
  - kuramoto
  - networkx
  - p_tqdm
