"""
Script recorder for the SMdRQA UI.

Every action taken in the UI appends an equivalent block of plain Python
to a :class:`ScriptRecorder`, so the whole interactive session can be
downloaded as a standalone, seeded, reproducible ``.py`` script.
"""

import datetime


class ScriptRecorder:
    """Accumulates Python code blocks mirroring UI actions.

    Parameters
    ----------
    seed : int
        Random seed chosen in the UI.  Baked into the script header so
        rerunning the exported file reproduces the session exactly.

    Examples
    --------
    >>> rec = ScriptRecorder(seed=42)
    >>> rec.record("x = np.arange(10)", comment="Create data")
    >>> print(rec.script())  # doctest: +SKIP
    """

    HEADER_TEMPLATE = '''\
"""
SMdRQA reproducibility script.

Auto-generated by the SMdRQA UI on {timestamp}.
Rerunning this file reproduces every analysis performed in the UI
session, including random-seed-dependent steps.
"""

import os

import numpy as np
import pandas as pd

from SMdRQA.RQA2 import RQA2, RQA2_simulators, RQA2_tests, RQA2_ml
from SMdRQA.ui.simulate import sample_regime_values, simulate_signal

SEED = {seed}
np.random.seed(SEED)

signals, ids, labels = [], [], []
'''

    def __init__(self, seed):
        self.seed = int(seed)
        self.created = datetime.datetime.now()
        self._blocks = []

    def record(self, code, comment=None):
        """Append one code block, optionally preceded by a # comment."""
        block = code.strip('\n')
        if comment:
            block = f"# {comment}\n{block}"
        self._blocks.append(block)

    def clear(self):
        """Drop all recorded blocks (header is kept)."""
        self._blocks = []

    @property
    def n_blocks(self):
        return len(self._blocks)

    def script(self):
        """Return the full script text (header + all recorded blocks)."""
        header = self.HEADER_TEMPLATE.format(
            timestamp=self.created.strftime('%Y-%m-%d %H:%M:%S'),
            seed=self.seed,
        )
        return "\n\n".join([header] + self._blocks) + "\n"
