homepage: "https://github.com/SwaragThaikkandi/SMdRQA.git"
language: python
primary_contact: "swaragthaikkandi@gmail.com"
auto_ccs:
  - "swaragtgithub@gmail.com"
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
main_repo: 'https://github.com/SwaragThaikkandi/SMdRQA.git'
