name: autopep8

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Manual trigger

jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Install autopep8
        run: pip install autopep8

      - name: autopep8
        id: autopep8
        run: |
          autopep8 --exit-code --recursive --in-place --aggressive --aggressive .

      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name ${{ secrets.GIT_USER_NAME }}
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
          git commit -am "Automated autopep8 fixes"
          git push
