name: Python Package CI/CD

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Change to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to GitHub Package Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Change to your main branch name
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python -m pip install --upgrade twine
          python -m twine upload --repository-url https://pypi.pkg.github.com/${{ github.repository_owner }}/${{ github.repository_name }} dist/*
