name: "Generate Coverage Report and Upload to Codecov"

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  coverage:
    name: "Python Tests with Coverage and Codecov Upload"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Adjust Python version as needed

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage

      - name: "Run tests and collect coverage"
        run: |
          coverage run -m pytest tests/
          coverage report -m
          coverage xml -o coverage.xml

      - name: "Save coverage report as artifact"
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Add your Codecov token as a secret
          file: coverage.xml
          flags: unittests  # Optional, specify flags for filtering coverage

