name: codecov

# Global YAML [lower on hierarchy]
coverage:
  round: down
  precision: 5

# Repository YAML [higher on hierarchy]

coverage:
  round: up
  range: 0..10

# Used in Codecov after updating
coverage:
  round: up
  range: 0..10
  precision: 5
comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment
  
component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doesn't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: RQA_functions
      paths:
        - .*/RQA_functions.py
    - component_id: utils
      paths:
        - .*/utils.py
