name: Issue Management Workflow

on:
  issues:
    types: [opened, edited]

jobs:
  process_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue is labeled correctly
        id: check_labels
        run: |
          if [[ ${{ github.event.issue.labels }} != *"bug"* ]]; then
            echo "::set-output name=needs_bug_label::true"
          fi

      - name: Add "needs-bug-label" label if necessary
        if: steps.check_labels.outputs.needs_bug_label == 'true'
        run: |
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels" \
            -d '["needs-bug-label"]'

      - name: Close issue if labeled "done"
        if: github.event.issue.labels.*.name == 'done'
        run: |
          curl \
            -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" \
            -d '{"state":"closed"}'
