name: Issue Management Workflow

on:
  issues:
    types: [opened, edited]

jobs:
  process_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue is labeled correctly
        id: check_labels
        run: |
          if [[ ${{ github.event.issue.labels }} != *"bug"* ]]; then
            echo "::set-output name=needs_bug_label::true"
          fi

      - name: Add "needs-bug-label" label if necessary
        if: steps.check_labels.outputs.needs_bug_label == 'true'
        uses: actions/github-script@v5
        with:
          script: |
            github.issues.addLabels({
              issue_number: ${{ github.event.issue.number }},
              labels: ['needs-bug-label']
            })

      - name: Close issue if labeled "done"
        if: github.event.issue.labels.*.name == 'done'
        uses: actions/github-script@v5
        with:
          script: |
            github.issues.update({
              issue_number: ${{ github.event.issue.number }},
              state: 'closed'
            })
