name: Metrics

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Example configuration for more elaborate metrics
          config: |
            template: default
            title: "GitHub Metrics Report"
            commits: { range: "12mo" }
            lines: 100
            languages: ["python", "javascript", "html", "css"]
            repositories: { exclude: "^lowlighter/metrics$" }
            activity: { commits: true, issues: true, pull_requests: true }
            community: true
            dependencies: true
            traffic: true
            details: true
            hide: "stars"
            base: "main"
            plugins:
              - activity
              - community
              - dependencies
              - traffic
              - details
            pull_requests:
              filters:
                categories:
                  - name: "Security Updates"
                    conditions: "label:security"
                  - name: "Feature Development"
                    conditions: "-label:security"
                  # Add more categories as needed

