name: publish_conda

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Debug directory structure
      run: ls -R  # List all files recursively
    - name: publish-to-conda
      uses: maxibor/conda-package-publish-action@v1.1
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      with:
        subDir: 'conda'  # <<< Double-check for typos here!

