name: Pull Request Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: PR Description
        uses: platisd/openai-pr-description@master
        with:
          github_token: ${{ secrets.PR_Metrics_Access_Token }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
      
      - name: GitHub Actions ChatGPT PR Reviewer
        uses: osl-incubator/github-actions-chatgpt-pr-reviewer@1.0.4
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}  # required
          openai_model: 'gpt-4-1106-preview'  # optional
          openai_temperature: 0.5  # optional
          openai_max_tokens: 2048  # optional
          openai_extra_criteria: |  # optional, use `;` for separate the criteria items
            - prefer readable variable name instead of short names like `k` and `v`, when apply;
            - verify `SOLID` principles design pattern violations, when apply;
          github_token: ${{ secrets.PR_Metrics_Access_Token }}  # required
          github_pr_id: ${{ github.event.number }}  # required

      - name: Complete Review
        run: |
          echo "Review completed for pull request"
