name: Snyk Security Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Authentication
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Snyk Code Analysis
        run: snyk code test --sarif > snyk-code.sarif || true

      - name: Snyk Open Source Scan
        run: snyk monitor --all-projects

      - name: Snyk IaC Scan
        run: snyk iac test --report || true

      - name: Build Docker Image
        run: docker build -t my-app:${{ github.sha }} .

      - name: Snyk Container Scan
        run: snyk container monitor my-app:${{ github.sha }} --file=Dockerfile

      - name: Upload Code Scanning Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
